### PR TITLE
Faster log

### PR DESCRIPTION
**Pull request by jonas-lj**
Faster logarithms for fixed point numbers

### CODE REVIEW

**Comment by n1v0lg** [comment]
Currently the result precision is hard-coded to 8 in the tests.

Is there a manageable way to guarantee result precision that matches our fixed point precision value instead?

**Comment by jonas-lj** [comment]
You're right. However, the precision depends strongly on the input. I could write some documentation about the expected precision depending on the input size?

**Comment by n1v0lg** [comment]
> You're right. However, the precision depends strongly on the input. I could write some documentation about the expected precision depending on the input size?

Yep, that would be great.

**Comment by jonas-lj** [comment]
I added a lengthy and rather mathy javadoc explaining the error and how it can be compensated for for large inputs.

**Pull request merged**
